- hosts: all
  user: root
  become: yes
  become_user: root


  pre_tasks: []

  roles:
  - ansible-os-hardening

  tasks:

  - name: Add pub to authorizedKeys
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', 'id_rsa_cyber.pub') }}"
    tags:
    - key
